_base_ = ["./bh_sdc_boundary_hazard_sparse_dense_local_precheck.py"]


variant_id = "BH-SDC-BoundaryHazard-SparseDense-FullTrainCandidate"
route_id = "bh_sdc_boundary_hazard_sparse_dense"
route_label = "DIVERGENT_INNOVATION_BH_SDC_DO_NOT_MERGE_WITH_C3"
stage_id = "bh_sdc_boundary_hazard_sparse_dense_full_train_candidate_n16r4"

experiment_scope = dict(
    variant_id=variant_id,
    route=route_id,
    route_label=route_label,
    route_family="BH_SDC_DIVERGENT_INNOVATION_ROUTE",
    combo_status="NO_COMBO_ROUTE_APPROVED",
    stage=stage_id,
    formal_train_candidate=True,
    full_train_candidate_only=True,
    local_synthetic_gate_only=False,
    pro_decision="GO_WITH_CONSTRAINTS_IMPLEMENT_BH_SDC_LOCAL_PROTOTYPE_ONLY",
    pro_code_or_launch_approval=False,
    launch_status="locked_until_major_code_review_pro_gate_and_subagent_final_review",
    complete_training_required=True,
    metric_claim_allowed=False,
    deploy_claim_allowed=False,
    runtime_flops_claim_allowed=False,
    paper_claim_allowed=False,
)

bh_sdc_gate = dict(
    route=route_id,
    route_label=route_label,
    stage=stage_id,
    default_off=True,
    requires_launch_gate=True,
    launch_gate_passed=False,
    allow_remote_sync=False,
    allow_slurm=False,
    allow_gpu=False,
    allow_tools_train=False,
    allow_tools_test=False,
    allow_detector_map=False,
    allow_train_validation_map=False,
    allow_long_training=False,
    allow_precheck_only=True,
    allow_dataset_access=False,
    allow_pretrained_initialization=False,
    allow_checkpoint_write=False,
    allow_checkpoint_load=False,
    allow_resume=False,
    allow_raw_prediction_cache=False,
    allow_metric_claim=False,
    allow_paper_claim=False,
    allowed_entrypoints=(),
    entrypoint_gate_context=dict(
        required=True,
        gate_json_env="OPENTAD_BH_SDC_GATE_JSON",
        gate_sha256_env="OPENTAD_BH_SDC_GATE_SHA256",
        active_manifest_sha256_env="OPENTAD_BH_SDC_ACTIVE_MANIFEST_SHA256",
        resolved_config_sha256_env="OPENTAD_BH_SDC_RESOLVED_CONFIG_SHA256",
        require_resolved_config_sha256=True,
        allowed_decisions=(),
        strict_payload_validation=True,
        forbidden_true_keys=(
            "tools_train",
            "allow_tools_train",
            "tools_test",
            "allow_tools_test",
            "detector_map",
            "allow_detector_map",
            "formal_eval",
            "allow_formal_eval",
            "remote_sync",
            "allow_remote_sync",
            "slurm",
            "allow_slurm",
            "gpu",
            "allow_gpu",
            "long_training",
            "allow_long_training",
            "checkpoint_load",
            "allow_checkpoint_load",
            "resume",
            "allow_resume",
            "raw_prediction_cache",
            "allow_raw_prediction_cache",
            "prediction_cache",
            "allow_prediction_cache",
            "load_from_raw_predictions",
            "save_raw_prediction",
            "uses_teacher",
            "uses_oracle",
            "uses_test_gt",
            "metric_claim_allowed",
            "paper_claim_allowed",
            "runtime_flops_claim_allowed",
            "deploy_claim_allowed",
        ),
    ),
    metric_claim_allowed=False,
    paper_claim_allowed=False,
    runtime_flops_claim_allowed=False,
    deploy_claim_allowed=False,
)

work_dir = "exps/thumos/adatad/bh_sdc_boundary_hazard_sparse_dense_full_train_candidate_n16r4"
