_base_ = ["./boundary_microscope_acquisition_local_precheck.py"]


route_label = "DIVERGENT_INNOVATION_BOUNDARY_MICROSCOPE_DO_NOT_MERGE_WITH_C3"
route_id = "boundary_microscope_acquisition"
stage_id = "full_train_candidate_n16r4"
variant_id = "Boundary-Microscope-Acquisition-Full-Train-Candidate-N16R4"
target_len = 384
window_size = 768

experiment_scope = dict(
    route=route_id,
    stage=stage_id,
    variant_id=variant_id,
    route_label=route_label,
    changed_surface="input_sampling_dynamic_boundary_packet_acquisition",
    candidate_status="implementation_prepared_but_train_locked",
    strict_budget_family="up_to_384_selected_frames_from_768_dense_window",
    deploy_time_inputs_only=True,
    test_time_gt_allowed=False,
    teacher_allowed=False,
    raw_prediction_cache_allowed=False,
    paper_claim_allowed=False,
)

boundary_microscope_gate = dict(
    route=route_id,
    stage=stage_id,
    route_label=route_label,
    allowed_decision="ALLOW_BOUNDARY_MICROSCOPE_FULL_TRAIN",
    requires_gate_json=True,
    allow_precheck_only=False,
    allow_tools_train=True,
    allow_tools_test=False,
    allow_remote_sync=False,
    allow_slurm=False,
    allow_gpu=False,
    allow_full_train=False,
    allow_raw_prediction=False,
    load_from_raw_predictions=False,
    save_raw_prediction=False,
    metric_claim_allowed=False,
    paper_claim_allowed=False,
    current_gate_cannot_authorize_remote_sync_or_full_train=True,
    future_full_train_requires_separate_decision=True,
    entrypoint_gate_context=dict(
        required=True,
        gate_json_env="OPENTAD_BOUNDARY_MICROSCOPE_ENTRYPOINT_GATE_JSON",
        gate_sha256_env="OPENTAD_BOUNDARY_MICROSCOPE_ENTRYPOINT_GATE_SHA256",
        active_manifest_sha256_env="OPENTAD_BOUNDARY_MICROSCOPE_ACTIVE_MANIFEST_SHA256",
        resolved_config_sha256_env="OPENTAD_BOUNDARY_MICROSCOPE_RESOLVED_CONFIG_SHA256",
        require_resolved_config_sha256=True,
        allowed_decisions=("ALLOW_BOUNDARY_MICROSCOPE_FULL_TRAIN",),
        strict_payload_validation=True,
        required_exact_values=dict(
            route=route_id,
            route_label=route_label,
            budget=target_len,
            dense_window_size=window_size,
            user_override_statement="USER_EXPLICITLY_REQUESTED_BOUNDARY_MICROSCOPE_FULL_TRAIN_CANDIDATE_ON_2026-06-24",
        ),
        required_true_keys=(
            "allow_tools_train",
            "allow_slurm",
            "allow_gpu",
            "allow_full_train",
        ),
        required_false_keys=(
            "allow_precheck_only",
            "allow_tools_test",
            "allow_remote_sync",
            "allow_raw_prediction",
            "load_from_raw_predictions",
            "save_raw_prediction",
            "test_time_gt_allowed",
            "teacher_allowed",
            "raw_prediction_cache_allowed",
            "uses_gt_at_test",
            "uses_teacher",
            "uses_raw_prediction_cache",
            "metric_claim_allowed",
            "paper_claim_allowed",
        ),
        forbidden_true_keys=(
            "tools_train",
            "tools_test",
            "allow_tools_test",
            "direct_tools_test",
            "remote_sync",
            "allow_remote_sync",
            "sbatch",
            "allow_sbatch",
            "gpu_train",
            "allow_gpu_train",
            "raw_prediction",
            "allow_raw_prediction",
            "raw_predictions",
            "allow_raw_predictions",
            "raw_prediction_cache",
            "allow_raw_prediction_cache",
            "prediction_cache",
            "allow_prediction_cache",
            "load_from_raw_predictions",
            "allow_load_from_raw_predictions",
            "save_raw_prediction",
            "allow_save_raw_prediction",
            "metric",
            "metric_claim",
            "allow_metric_claim",
            "metric_claim_allowed",
            "paper_claim",
            "allow_paper_claim",
            "paper_claim_allowed",
            "runtime_claim",
            "allow_runtime_claim",
            "deploy_claim",
            "allow_deploy_claim",
            "uses_gt_at_test",
            "uses_test_gt",
            "uses_teacher",
            "uses_oracle",
        ),
        unknown_key_policy="reject_unknown_except_explicit_harmless_metadata",
        harmless_metadata_keys=("note", "review_id", "run_tag"),
    ),
    allowed_entrypoints=("tools/train.py",),
    forbidden_entrypoints=("tools/test.py", "scp", "rsync"),
)

model = dict(
    frame_selector=dict(
        type="BoundaryMicroscopeAcquisitionRoute",
        route_label=route_label,
        meta_key="boundary_microscope_acquisition_plan",
        target_len=target_len,
        dense_window_size=window_size,
        microscope_radius=3,
        microscope_stride=1,
        anchor_stride=24,
        max_dense_gap=8,
        max_start_hazards=4,
        max_end_hazards=4,
        action_threshold=0.15,
    )
)

workflow = dict(
    logging_interval=50,
    checkpoint_interval=60,
    val_loss_interval=-1,
    val_eval_interval=2,
    val_start_epoch=40,
    end_epoch=60,
)

work_dir = "exps/thumos/adatad/boundary_microscope_acquisition_full_train_candidate_n16r4"
