variant_id = "EventSurpriseTemporalAcquisition-FailClosedFullTrainCandidate"
route_label = "DIVERGENT_INNOVATION_EVENT_SURPRISE_DO_NOT_MERGE_WITH_C3"
meta_key = "event_surprise_acquisition_plan"

window_size = 384
dense_window_size = 768
descriptor_dim = 12

experiment_scope = dict(
    variant_id=variant_id,
    route="event_surprise_temporal_acquisition",
    route_label=route_label,
    stage="full_train_candidate_locked",
    protocol_family="event_surprise_sparse_acquisition_contract",
    meta_key=meta_key,
    detector_stack="adatad_actionformer_adapter_candidate",
    selection_surface="deploy_visible_temporal_features",
    selection_timing="pre_detector_selected_axis",
    acquisition_unit="frame_or_snippet",
    detector_integration="pre_detector_selected_axis_with_gt_remap",
    event_surprise_core=(
        "Locked candidate for later review: select sparse temporal evidence from "
        "deploy-visible temporal surprise, motion/change, uncertainty, redundancy, "
        "coverage anchors, and a max-gap guard."
    ),
    changes_input_sampling=True,
    changes_dynamic_budget_policy=False,
    changes_token_compression=False,
    changes_adapter_backbone_neck=False,
    changes_detector_head=False,
    changes_loss_assignment=False,
    changes_test_time_post_processing=False,
    uses_pc_ot_mras_detector_bridge=False,
    uses_test_gt=False,
    uses_oracle=False,
    uses_teacher=False,
    uses_raw_prediction=False,
    complete_training_required=False,
    metric_claim_allowed=False,
    deploy_claim_allowed=False,
    runtime_flops_claim_allowed=False,
    paper_claim_allowed=False,
)

event_surprise_acquisition_gate = dict(
    route="event_surprise_temporal_acquisition",
    route_label=route_label,
    stage="full_train_candidate_locked",
    default_off=True,
    explicit_config_opt_in=True,
    launch_gate_passed=False,
    formal_train_candidate=True,
    full_train_candidate=True,
    allow_remote_sync=False,
    allow_slurm=False,
    allow_gpu=False,
    allow_tools_train=False,
    allow_tools_test=False,
    allow_detector_training=False,
    allow_detector_map=False,
    allow_train_validation_map=False,
    allow_long_training=False,
    allow_full_train=False,
    allow_precheck_only=False,
    allow_raw_prediction=False,
    allow_raw_predictions=False,
    allow_metric_claim=False,
    metric_claim_allowed=False,
    allow_paper_claim=False,
    paper_claim_allowed=False,
    allow_runtime_claim=False,
    runtime_flops_claim_allowed=False,
    allow_deploy_claim=False,
    deploy_claim_allowed=False,
    allowed_entrypoints=(),
    entrypoint_gate_context=dict(
        required=True,
        allowed_decisions=(),
        strict_payload_validation=True,
        unknown_key_policy="reject_unknown_except_explicit_harmless_metadata",
        forbidden_true_keys=(
            "remote_sync",
            "allow_remote_sync",
            "slurm",
            "allow_slurm",
            "gpu",
            "allow_gpu",
            "tools_train",
            "allow_tools_train",
            "tools_test",
            "allow_tools_test",
            "full_train",
            "allow_full_train",
            "detector_training",
            "allow_detector_training",
            "detector_map",
            "allow_detector_map",
            "formal_eval",
            "allow_formal_eval",
            "checkpoint_load",
            "allow_checkpoint_load",
            "resume",
            "allow_resume",
            "load_from",
            "allow_load_from",
            "raw_prediction",
            "allow_raw_prediction",
            "raw_predictions",
            "allow_raw_predictions",
            "raw_prediction_cache",
            "allow_raw_prediction_cache",
            "prediction_cache",
            "allow_prediction_cache",
            "load_from_raw_predictions",
            "allow_load_from_raw_predictions",
            "save_raw_prediction",
            "allow_save_raw_prediction",
            "save_raw_predictions",
            "allow_save_raw_predictions",
            "uses_teacher",
            "uses_oracle",
            "uses_test_gt",
            "uses_raw_prediction",
            "metric_claim",
            "allow_metric_claim",
            "metric_claim_allowed",
            "paper_claim",
            "allow_paper_claim",
            "paper_claim_allowed",
            "runtime_claim",
            "allow_runtime_claim",
            "flops_claim",
            "allow_flops_claim",
            "runtime_flops_claim",
            "allow_runtime_flops_claim",
            "runtime_flops_claim_allowed",
            "deploy_claim",
            "allow_deploy_claim",
            "deploy_claim_allowed",
        ),
    ),
)

model = dict(
    frame_selector=dict(
        type="EventSurpriseTemporalAcquisitionSelector",
        in_dim=descriptor_dim,
        target_len=window_size,
        max_gap=8,
        coverage_anchor_count=64,
        surprise_topk=224,
        surprise_weight=1.0,
        motion_weight=0.85,
        uncertainty_weight=0.60,
        redundancy_weight=0.40,
        input_layout="bct",
        remap_gt_to_selected_axis=True,
        route_label=route_label,
        meta_key=meta_key,
    ),
)

inference = dict(load_from_raw_predictions=False, save_raw_prediction=False)

work_dir = "local_runs/event_surprise_temporal_acquisition_full_train_candidate_locked"
