_base_ = ["./pc_ot_mras_prebackbone_c3_pro_boundary_reader_full_train_candidate_n16r4.py"]


variant_id = "C3-IntervalScoreFirst-BoundaryPacket-OriginalAdaTAD"
route_id = "pc_ot_mras_prebackbone_c3_interval_score_first"
stage_id = "c3_interval_score_first_full_train_candidate_n16r4"
route_label = "C3_ORIGINAL_OPTIMIZATION_ROUTE"

experiment_scope = dict(
    variant_id=variant_id,
    route=route_id,
    stage=stage_id,
    route_label=route_label,
    detector_stack="original_adatad_actionformer_adapter",
    backend="OriginalAdaTAD",
    selection_surface="pre_backbone_raw_frame",
    selection_timing="online_before_backbone",
    acquisition_unit="frame",
    budget_protocol="fixed384_over_dense768_interval_score_first_boundary_packet_global_rank_st",
    selector_reader="PCOTMRASBoundaryDifficultyTemporalFrameScout",
    selection_strategy="interval_score_first_packet",
    interval_boundary_budget_ratio=0.50,
    interval_candidate_topk=24,
    boundary_lock=(
        "C3_INTERVAL_SCORE_FIRST first scores start/end/action intervals from deploy-visible "
        "low-resolution scout features, then allocates boundary and interior packets. "
        "Hard forward emits sorted unique real dense frames only and keeps the original "
        "AdaTAD/ActionFormer detector, evaluator, and post-processing unchanged."
    ),
    rank_transport_surrogate="global_softmax",
    uses_p2=False,
    uses_offline_ledger=False,
    uses_teacher=False,
    uses_test_gt=False,
    uses_raw_prediction_cache=False,
    changes_input_sampling=True,
    changes_detector_head=False,
    changes_neck=False,
    changes_loss_assignment=False,
    changes_post_processing=False,
    metric_claim_allowed=False,
    deploy_claim_allowed=False,
    runtime_flops_claim_allowed=False,
    paper_claim_allowed=False,
    full_train_approval=False,
)

pc_ot_mras_prebackbone_e2e_acquisition_gate = dict(
    _delete_=True,
    route=route_id,
    stage=stage_id,
    route_label=route_label,
    default_off=True,
    explicit_config_opt_in=True,
    formal_train_candidate=False,
    remote_precheck_only_candidate=True,
    selection_surface="pre_backbone_raw_frame",
    selection_timing="online_before_backbone",
    acquisition_unit="frame",
    full_joint_selector_detector_training=False,
    offline_ledger=False,
    post_projection_bridge=False,
    allow_detector_training=False,
    requires_launch_gate=True,
    launch_gate_passed=False,
    allow_remote_sync=True,
    allow_precheck_only=True,
    allow_slurm=False,
    allow_gpu=False,
    allow_tools_train=False,
    allow_tools_test=False,
    allow_detector_map=False,
    allow_train_validation_map=False,
    allow_long_training=False,
    allow_prebackbone_frame_selector=True,
    allow_joint_selector_detector_training=False,
    allow_dataset_access=False,
    allow_pretrained_initialization=False,
    allow_checkpoint_write=False,
    allow_checkpoint_load=False,
    allow_resume=False,
    allow_raw_prediction_cache=False,
    selector_support_status="supported_by_prebackbone_frame_selector",
    entrypoint_gate_context=dict(
        required=True,
        allowed_decisions=("ALLOW_C3_INTERVAL_SCORE_FIRST_REMOTE_PRECHECK_ONLY",),
        strict_payload_validation=True,
        forbidden_true_keys=(
            "tools_train",
            "allow_tools_train",
            "tools_test",
            "allow_tools_test",
            "direct_tools_test",
            "detector_map",
            "allow_detector_map",
            "detector_training",
            "allow_detector_training",
            "train_validation_map",
            "allow_train_validation_map",
            "formal_eval",
            "allow_formal_eval",
            "long_training",
            "allow_long_training",
            "joint_selector_detector_training",
            "allow_joint_selector_detector_training",
            "dataset_access",
            "allow_dataset_access",
            "pretrained_initialization",
            "allow_pretrained_initialization",
            "slurm",
            "allow_slurm",
            "gpu",
            "allow_gpu",
            "checkpoint_write",
            "allow_checkpoint_write",
            "checkpoint_load",
            "allow_checkpoint_load",
            "resume",
            "allow_resume",
            "load_from",
            "allow_load_from",
            "offline_ledger",
            "allow_offline_ledger",
            "frozen_reader_ledger",
            "allow_frozen_reader_ledger",
            "post_projection_bridge",
            "allow_post_projection_bridge",
            "raw_prediction",
            "allow_raw_prediction",
            "raw_predictions",
            "allow_raw_predictions",
            "raw_prediction_cache",
            "allow_raw_prediction_cache",
            "prediction_cache",
            "allow_prediction_cache",
            "load_from_raw_predictions",
            "allow_load_from_raw_predictions",
            "save_raw_prediction",
            "allow_save_raw_prediction",
            "save_raw_predictions",
            "allow_save_raw_predictions",
            "uses_p2",
            "uses_teacher",
            "uses_oracle",
            "uses_test_gt",
            "uses_raw_prediction",
            "metric_claim",
            "allow_metric_claim",
            "metric_claim_allowed",
            "paper_claim",
            "allow_paper_claim",
            "paper_claim_allowed",
            "runtime_claim",
            "allow_runtime_claim",
            "flops_claim",
            "allow_flops_claim",
            "runtime_flops_claim",
            "allow_runtime_flops_claim",
            "runtime_flops_claim_allowed",
            "deploy_claim",
            "allow_deploy_claim",
            "deploy_claim_allowed",
        ),
    ),
    metric_claim_allowed=False,
    paper_claim_allowed=False,
    runtime_flops_claim_allowed=False,
    deploy_claim_allowed=False,
    full_train_approval=False,
    allowed_entrypoints=(),
)

model = dict(
    frame_selector=dict(
        selection_strategy="interval_score_first_packet",
        frame_score_st_surrogate="global_softmax",
        interval_boundary_budget_ratio=0.50,
        interval_candidate_topk=24,
        max_dense_gap=0,
        max_gap_guard_count=0,
        reader_regularizer_loss_weight=0.0,
    )
)

work_dir = "exps/thumos/adatad/pc_ot_mras_prebackbone_c3_interval_score_first_full_train_candidate_n16r4"
