_base_ = ["./input_random_fixed_50pct_c3_physical_grid_actionformer_precheck.py"]

variant_id = "C3-PhysicalGridActionFormer-PreBackbone-OriginalAdaTAD"
route_id = "pc_ot_mras_prebackbone_c3_physical_grid_actionformer"
stage_id = "c3_physical_grid_actionformer_full_train_n16r4"

route_label = "C3_ORIGINAL_OPTIMIZATION_ROUTE"
route_family = "C3_MAINLINE_OPTIMIZATION"
candidate_name = stage_id
window_size = 384
dense_window_size = 768
scale_factor = 1

experiment_scope = dict(
    variant_id=variant_id,
    route_family=route_family,
    route=route_id,
    stage=stage_id,
    detector_stack="physical_grid_actionformer_adapter",
    backend="OriginalAdaTAD_ActionFormerPhysicalGrid",
    selection_surface="pre_backbone_raw_frame",
    selection_timing="online_before_backbone",
    acquisition_unit="frame",
    budget_protocol="fixed384_over_dense768_prebackbone_frame_score_first_physical_grid_actionformer",
    selector_reader="PCOTMRASBoundaryDifficultyTemporalFrameScout",
    selection_strategy="frame_score_topk",
    temporal_grid_mode="physical",
    uses_p2=False,
    uses_offline_ledger=False,
    uses_teacher=False,
    uses_test_gt=False,
    uses_raw_prediction_cache=False,
    changes_input_sampling=True,
    changes_dynamic_budget_policy=False,
    changes_token_compression=False,
    changes_adapter_backbone=False,
    changes_detector_head=True,
    changes_loss_assignment=True,
    changes_post_processing=False,
    metric_claim_allowed=False,
    deploy_claim_allowed=False,
    runtime_flops_claim_allowed=False,
    paper_claim_allowed=False,
)

protocol_flags = dict(
    _delete_=True,
    precheck_only=False,
    formal_train_candidate=True,
    changed_surface="input_sampling_plus_head_temporal_geometry",
    selector_changed=True,
    dynamic_budget_changed=False,
    token_compression_changed=False,
    adapter_backbone_changed=False,
    detector_head_logic_changed=True,
    loss_assignment_changed=True,
    post_processing_changed=False,
    uses_p2_head=False,
    uses_raw_prediction_cache=False,
    uses_teacher=False,
    uses_test_gt=False,
    uses_offline_ledger=False,
    tools_test_allowed=False,
    tools_train_allowed=True,
    remote_sync_allowed=True,
    slurm_allowed=True,
    metric_claim_allowed=False,
    paper_claim_allowed=False,
)

pc_ot_mras_prebackbone_e2e_acquisition_gate = dict(
    route=route_id,
    stage=stage_id,
    default_off=True,
    explicit_config_opt_in=True,
    formal_train_candidate=True,
    remote_precheck_only_candidate=False,
    selection_surface="pre_backbone_raw_frame",
    selection_timing="online_before_backbone",
    acquisition_unit="frame",
    full_joint_selector_detector_training=True,
    offline_ledger=False,
    post_projection_bridge=False,
    allow_detector_training=True,
    requires_launch_gate=True,
    launch_gate_passed=True,
    allow_remote_sync=True,
    allow_precheck_only=True,
    allow_slurm=True,
    allow_gpu=True,
    allow_tools_train=True,
    allow_tools_test=False,
    allow_detector_map=False,
    allow_train_validation_map=True,
    allow_long_training=True,
    allow_prebackbone_frame_selector=True,
    allow_joint_selector_detector_training=True,
    allow_dataset_access=True,
    allow_pretrained_initialization=True,
    allow_checkpoint_write=True,
    allow_checkpoint_load=False,
    allow_resume=False,
    allow_raw_prediction_cache=False,
    selector_support_status="requires_prebackbone_frame_selector_runtime",
    entrypoint_gate_context=dict(
        required=True,
        gate_json_env="OPENTAD_C3_PHYSICAL_GRID_GATE_JSON",
        gate_sha256_env="OPENTAD_C3_PHYSICAL_GRID_GATE_SHA256",
        active_manifest_sha256_env="OPENTAD_C3_PHYSICAL_GRID_ACTIVE_MANIFEST_SHA256",
        resolved_config_sha256_env="OPENTAD_C3_PHYSICAL_GRID_RESOLVED_CONFIG_SHA256",
        require_resolved_config_sha256=True,
        allowed_decisions=("ALLOW_C3_PHYSICAL_GRID_FULL_TRAIN",),
        strict_payload_validation=True,
        required_exact_values=dict(
            route=route_id,
            variant_id=variant_id,
            stage=stage_id,
            execution_mode="train",
            budget=384,
            dense_window_size=768,
        ),
        required_true_keys=(
            "allow_tools_train",
            "allow_slurm",
            "allow_gpu",
            "single_gpu",
            "allow_prebackbone_frame_selector",
            "allow_detector_training",
            "allow_train_validation_map",
            "allow_long_training",
            "allow_pretrained_initialization",
            "allow_checkpoint_write",
        ),
        forbidden_true_keys=(
            "tools_test",
            "allow_tools_test",
            "direct_tools_test",
            "detector_map",
            "allow_detector_map",
            "checkpoint_load",
            "allow_checkpoint_load",
            "resume",
            "allow_resume",
            "offline_ledger",
            "allow_offline_ledger",
            "post_projection_bridge",
            "allow_post_projection_bridge",
            "raw_prediction_cache",
            "allow_raw_prediction_cache",
            "load_from_raw_predictions",
            "save_raw_prediction",
            "uses_p2",
            "uses_teacher",
            "uses_test_gt",
            "uses_raw_prediction_cache",
            "metric_claim",
            "metric_claim_allowed",
            "paper_claim",
            "paper_claim_allowed",
            "runtime_flops_claim",
            "runtime_flops_claim_allowed",
            "deploy_claim",
            "deploy_claim_allowed",
        ),
    ),
    metric_claim_allowed=False,
    paper_claim_allowed=False,
    runtime_flops_claim_allowed=False,
    deploy_claim_allowed=False,
    allowed_entrypoints=("tools/train.py",),
)

model = dict(
    frame_selector=dict(
        type="PCOTMRASPreBackboneFrameSelector",
        target_len=window_size,
        dense_window_size=dense_window_size,
        descriptor_dim=3 * 32 * 32,
        selection_unit=1,
        remap_gt_to_selected_axis=False,
        selection_strategy="frame_score_topk",
        scout_feature_source="compressed_pixels",
        scout_spatial_size=32,
        reader=dict(
            type="PCOTMRASBoundaryDifficultyTemporalFrameScout",
            in_dim=3 * 32 * 32,
            hidden_dim=96,
            num_slots=window_size,
            temporal_layers=4,
            temporal_kernel_size=5,
            dilations=(1, 2, 4, 8),
            dropout=0.10,
        ),
    ),
    rpn_head=dict(
        type="ActionFormerHead",
        physical_grid_actionformer=dict(
            enabled=True,
            required=True,
            strict=True,
            eps=1.0e-6,
            diagnostic=dict(
                emit_score_iou_entry=True,
                emit_proposal_cap_entry=True,
                emit_selected_vs_physical_axis_entry=True,
            ),
        ),
        assignment_debug=dict(enabled=True),
    ),
    backbone=dict(
        backbone=dict(total_frames=window_size),
        custom=dict(
            pre_processing_pipeline=[
                dict(
                    type="Rearrange",
                    keys=["frames"],
                    ops="b n c (t1 t) h w -> (b t1) n c t h w",
                    t1=24,
                )
            ],
            post_processing_pipeline=[
                dict(type="Reduce", keys=["feats"], ops="b n c t h w -> b c t", reduction="mean"),
                dict(type="Rearrange", keys=["feats"], ops="(b t1) c t -> b c (t1 t)", t1=24),
                dict(type="Interpolate", keys=["feats"], size=window_size),
            ],
        ),
    ),
    projection=dict(max_seq_len=window_size),
)

dataset = dict(
    train=dict(
        pipeline=[
            dict(type="PrepareVideoInfo", format="mp4"),
            dict(type="mmaction.DecordInit", num_threads=4),
            dict(
                type="LoadFrames",
                num_clips=1,
                method="random_trunc",
                trunc_len=dense_window_size,
                trunc_thresh=0.75,
                crop_ratio=[0.9, 1.0],
                scale_factor=scale_factor,
                remap_gt_to_selected_axis=False,
            ),
            dict(type="mmaction.DecordDecode"),
            dict(type="mmaction.Resize", scale=(-1, 182)),
            dict(type="mmaction.RandomResizedCrop"),
            dict(type="mmaction.Resize", scale=(160, 160), keep_ratio=False),
            dict(type="mmaction.Flip", flip_ratio=0.5),
            dict(type="mmaction.ImgAug", transforms="default"),
            dict(type="mmaction.ColorJitter"),
            dict(type="mmaction.FormatShape", input_format="NCTHW"),
            dict(type="ConvertToTensor", keys=["imgs", "gt_segments", "gt_labels"]),
            dict(type="Collect", inputs="imgs", keys=["masks", "gt_segments", "gt_labels"]),
        ],
    ),
    val=dict(
        window_size=dense_window_size,
        pipeline=[
            dict(type="PrepareVideoInfo", format="mp4"),
            dict(type="mmaction.DecordInit", num_threads=4),
            dict(
                type="LoadFrames",
                num_clips=1,
                method="sliding_window",
                scale_factor=scale_factor,
                remap_gt_to_selected_axis=False,
            ),
            dict(type="mmaction.DecordDecode"),
            dict(type="mmaction.Resize", scale=(-1, 160)),
            dict(type="mmaction.CenterCrop", crop_size=160),
            dict(type="mmaction.FormatShape", input_format="NCTHW"),
            dict(type="ConvertToTensor", keys=["imgs", "gt_segments", "gt_labels"]),
            dict(type="Collect", inputs="imgs", keys=["masks", "gt_segments", "gt_labels"]),
        ],
    ),
    test=dict(
        window_size=dense_window_size,
        pipeline=[
            dict(type="PrepareVideoInfo", format="mp4"),
            dict(type="mmaction.DecordInit", num_threads=4),
            dict(
                type="LoadFrames",
                num_clips=1,
                method="sliding_window",
                scale_factor=scale_factor,
                remap_gt_to_selected_axis=False,
            ),
            dict(type="mmaction.DecordDecode"),
            dict(type="mmaction.Resize", scale=(-1, 160)),
            dict(type="mmaction.CenterCrop", crop_size=160),
            dict(type="mmaction.FormatShape", input_format="NCTHW"),
            dict(type="ConvertToTensor", keys=["imgs"]),
            dict(type="Collect", inputs="imgs", keys=["masks"]),
        ],
    ),
)

workflow = dict(
    disable_checkpoint=False,
    logging_interval=50,
    checkpoint_interval=2,
    val_loss_interval=-1,
    val_eval_interval=2,
    val_start_epoch=40,
    end_epoch=60,
)

solver = dict(
    train=dict(batch_size=2, num_workers=2),
    val=dict(batch_size=2, num_workers=2),
    test=dict(batch_size=2, num_workers=2),
)

inference = dict(load_from_raw_predictions=False, save_raw_prediction=False)
post_processing = dict(save_dict=True)

work_dir = "exps/thumos/adatad/pc_ot_mras_prebackbone_c3_physical_grid_actionformer_full_train_n16r4"
