_base_ = ["./pc_ot_mras_prebackbone_e2e_frame_acquisition_actionformer_adapter_fixed50_candidate_n16r4.py"]

variant_id = "C3-F1-LR-TinyTransformer-ST-OriginalAdaTAD"

# Boundary lock for review: C3-F1 is a free frame-level 384-slot selector.
# It is not C2 320-uniform+64-residual, not a protected scaffold route, and
# not the future S80R16/cell96x4 route.

window_size = 384
dense_window_size = 768
selection_unit = 1
selection_unit2_supported = True
scout_spatial_size = 32
scout_descriptor_dim = 3 * scout_spatial_size * scout_spatial_size

experiment_scope = dict(
    variant_id=variant_id,
    route="pc_ot_mras_prebackbone_c3_f1_lr_tinytransformer_st_original_adatad",
    stage="c3_f1_lr_tinytransformer_st_original_adatad_local_candidate",
    detector_stack="original_adatad_actionformer_adapter",
    backend="OriginalAdaTAD",
    selection_surface="pre_backbone_raw_frame",
    selection_timing="online_before_backbone",
    acquisition_unit="frame",
    budget_protocol="fixed384_over_dense768_frame_level_candidate",
    boundary_lock=(
        "C3-F1 is free frame-level 384-slot compressed-pixel TinyTransformer ST selection; "
        "not protected scaffold, not C2 320+64, not S80R16/cell96x4."
    ),
    free_frame_level_selector=True,
    protected_scaffold=False,
    c2_320_uniform_plus_64_residual=False,
    s80r16_cell96x4_enabled=False,
    s80r16_cell96x4_note=(
        "Not S80R16/cell96x4. C3-F1 keeps one candidate per dense frame by default "
        "and uses 384 learned slots without protected uniform scaffold."
    ),
    selector_reader="PCOTMRASTinyTransformerFrameScout",
    selector_gradient="straight_through_hard_real_frames_soft_slot_logits",
    low_resolution_scout=True,
    scout_input="compressed_low_resolution_frame_pixels_before_videomae",
    scout_feature_source="compressed_pixels",
    scout_spatial_size=scout_spatial_size,
    selection_unit=selection_unit,
    selection_unit2_supported=selection_unit2_supported,
    uses_p2=False,
    uses_offline_ledger=False,
    uses_teacher=False,
    uses_test_gt=False,
    uses_raw_prediction_cache=False,
    changes_input_sampling=True,
    changes_detector_head=False,
    changes_neck=False,
    changes_loss_assignment=False,
    changes_training_window_protocol=True,
    deploy_claim_allowed=False,
    runtime_flops_claim_allowed=False,
    paper_claim_allowed=False,
)

pc_ot_mras_prebackbone_e2e_acquisition_gate = dict(
    _delete_=True,
    route="pc_ot_mras_prebackbone_c3_f1_lr_tinytransformer_st_original_adatad",
    stage="c3_f1_lr_tinytransformer_st_original_adatad_local_candidate_locked",
    default_off=True,
    explicit_config_opt_in=True,
    formal_train_candidate=False,
    selection_surface="pre_backbone_raw_frame",
    selection_timing="online_before_backbone",
    acquisition_unit="frame",
    full_joint_selector_detector_training=False,
    offline_ledger=False,
    post_projection_bridge=False,
    allow_detector_training=False,
    requires_launch_gate=True,
    launch_gate_passed=False,
    allow_remote_sync=False,
    allow_precheck_only=False,
    allow_slurm=False,
    allow_gpu=False,
    allow_tools_train=False,
    allow_tools_test=False,
    allow_detector_map=False,
    allow_train_validation_map=False,
    allow_long_training=False,
    allow_prebackbone_frame_selector=False,
    allow_joint_selector_detector_training=False,
    allow_dataset_access=False,
    allow_pretrained_initialization=False,
    allow_checkpoint_write=False,
    allow_checkpoint_load=False,
    allow_resume=False,
    selector_support_status="supported_by_prebackbone_frame_selector",
    entrypoint_gate_context=dict(
        required=True,
        allowed_decisions=(),
        strict_payload_validation=True,
        forbidden_true_keys=(
            "tools_train",
            "allow_tools_train",
            "tools_test",
            "allow_tools_test",
            "direct_tools_test",
            "detector_map",
            "allow_detector_map",
            "formal_eval",
            "allow_formal_eval",
            "remote_sync",
            "allow_remote_sync",
            "slurm",
            "allow_slurm",
            "gpu",
            "allow_gpu",
            "checkpoint_load",
            "allow_checkpoint_load",
            "resume",
            "allow_resume",
            "load_from",
            "allow_load_from",
            "offline_ledger",
            "allow_offline_ledger",
            "frozen_reader_ledger",
            "allow_frozen_reader_ledger",
            "post_projection_bridge",
            "allow_post_projection_bridge",
            "raw_prediction",
            "allow_raw_prediction",
            "raw_predictions",
            "allow_raw_predictions",
            "raw_prediction_cache",
            "allow_raw_prediction_cache",
            "prediction_cache",
            "allow_prediction_cache",
            "load_from_raw_predictions",
            "allow_load_from_raw_predictions",
            "save_raw_prediction",
            "allow_save_raw_prediction",
            "save_raw_predictions",
            "allow_save_raw_predictions",
            "uses_p2",
            "uses_teacher",
            "uses_oracle",
            "uses_test_gt",
            "uses_raw_prediction",
            "metric_claim",
            "allow_metric_claim",
            "metric_claim_allowed",
            "paper_claim",
            "allow_paper_claim",
            "paper_claim_allowed",
            "runtime_claim",
            "allow_runtime_claim",
            "flops_claim",
            "allow_flops_claim",
            "runtime_flops_claim",
            "allow_runtime_flops_claim",
            "runtime_flops_claim_allowed",
            "deploy_claim",
            "allow_deploy_claim",
            "deploy_claim_allowed",
        ),
    ),
    metric_claim_allowed=False,
    paper_claim_allowed=False,
    runtime_flops_claim_allowed=False,
    deploy_claim_allowed=False,
    allowed_entrypoints=(),
)

model = dict(
    frame_selector=dict(
        type="PCOTMRASPreBackboneFrameSelector",
        target_len=window_size,
        dense_window_size=dense_window_size,
        descriptor_dim=scout_descriptor_dim,
        scout_feature_source="compressed_pixels",
        scout_spatial_size=scout_spatial_size,
        selection_unit=selection_unit,
        selection_unit2_supported=selection_unit2_supported,
        protected_uniform_count=0,
        coverage_guard_count=0,
        transport_topk=1,
        eval_transport_topk=1,
        straight_through_downstream=True,
        remap_gt_to_selected_axis=True,
        aux_gt_acquisition_loss_weight=0.05,
        aux_value_loss_weight=0.0,
        aux_risk_loss_weight=0.0,
        aux_role_entropy_loss_weight=0.0,
        reader_regularizer_loss_weight=0.0,
        reader=dict(
            _delete_=True,
            type="PCOTMRASTinyTransformerFrameScout",
            in_dim=scout_descriptor_dim,
            hidden_dim=128,
            num_slots=window_size,
            num_layers=2,
            num_heads=4,
            dropout=0.0,
        ),
    ),
    backbone=dict(
        backbone=dict(total_frames=window_size),
    ),
    projection=dict(max_seq_len=window_size),
)

inference = dict(load_from_raw_predictions=False, save_raw_prediction=False)

work_dir = "exps/thumos/adatad/pc_ot_mras_prebackbone_c3_f1_lr_tinytransformer_st_original_adatad"
