_base_ = ["./pc_ot_mras_prebackbone_c3_f1_lr_tinytransformer_st_original_adatad.py"]

import os


variant_id = "C3-F1-LR-TinyTransformer-ST-OriginalAdaTAD"
route_id = "pc_ot_mras_prebackbone_c3_f1_lr_tinytransformer_st_original_adatad"
stage_id = "c3_f1_lr_tinytransformer_st_original_adatad_full_train_candidate"

window_size = 384
dense_window_size = 768
selection_unit = 1
scout_spatial_size = 32
scout_descriptor_dim = 3 * scout_spatial_size * scout_spatial_size

pretrained_path = os.environ.get(
    "PC_OT_MRAS_PREBACKBONE_C3_PRETRAINED_PATH",
    "pretrained/vit-small-p16_videomae-k400-pre_16x4x1_kinetics-400_my.pth",
)

experiment_scope = dict(
    _delete_=True,
    variant_id=variant_id,
    route=route_id,
    stage=stage_id,
    detector_stack="original_adatad_actionformer_adapter",
    backend="OriginalAdaTAD",
    selection_surface="pre_backbone_raw_frame",
    selection_timing="online_before_backbone",
    acquisition_unit="frame",
    budget_protocol="fixed384_over_dense768_frame_level_full_train",
    boundary_lock=(
        "C3 full train is free frame-level 384-slot compressed-pixel "
        "TinyTransformer ST selection before VideoMAE; not C2 320+64, not P2, "
        "not offline ledger, and not raw-cache evaluation."
    ),
    free_frame_level_selector=True,
    protected_scaffold=False,
    c2_320_uniform_plus_64_residual=False,
    s80r16_cell96x4_enabled=False,
    s80r16_cell96x4_note=(
        "Not S80R16/cell96x4. C3 full train keeps one candidate per dense frame "
        "and learns 384 frame-level slots without protected uniform scaffold."
    ),
    train_protocol="joint_selector_detector_fixed50_prebackbone_full_train",
    selector_reader="PCOTMRASTinyTransformerFrameScout",
    selector_gradient="straight_through_hard_real_frames_soft_slot_logits",
    selector_support_status="supported_by_prebackbone_frame_selector",
    reader_trainable=True,
    low_resolution_scout=True,
    scout_input="compressed_low_resolution_frame_pixels_before_videomae",
    scout_feature_source="compressed_pixels",
    scout_spatial_size=scout_spatial_size,
    selection_unit=selection_unit,
    uses_p2=False,
    uses_offline_ledger=False,
    uses_teacher=False,
    uses_test_gt=False,
    uses_raw_prediction_cache=False,
    changes_input_sampling=True,
    changes_detector_head=False,
    changes_neck=False,
    changes_loss_assignment=False,
    changes_post_processing=False,
    changes_training_window_protocol=True,
    complete_training_required=True,
    metric_claim_allowed=False,
    deploy_claim_allowed=False,
    runtime_flops_claim_allowed=False,
    paper_claim_allowed=False,
)

pc_ot_mras_prebackbone_e2e_acquisition_gate = dict(
    _delete_=True,
    route=route_id,
    stage=stage_id,
    default_off=False,
    explicit_config_opt_in=True,
    formal_train_candidate=True,
    selection_surface="pre_backbone_raw_frame",
    selection_timing="online_before_backbone",
    acquisition_unit="frame",
    full_joint_selector_detector_training=True,
    offline_ledger=False,
    post_projection_bridge=False,
    allow_detector_training=True,
    requires_launch_gate=True,
    launch_gate_passed=True,
    allow_remote_sync=True,
    allow_precheck_only=True,
    allow_slurm=True,
    allow_gpu=True,
    allow_tools_train=True,
    allow_tools_test=False,
    allow_detector_map=False,
    allow_train_validation_map=True,
    allow_long_training=True,
    allow_prebackbone_frame_selector=True,
    allow_joint_selector_detector_training=True,
    allow_dataset_access=True,
    allow_pretrained_initialization=True,
    allow_checkpoint_write=True,
    allow_checkpoint_load=False,
    allow_resume=False,
    selector_support_status="supported_by_prebackbone_frame_selector",
    entrypoint_gate_context=dict(
        required=True,
        gate_json_env="OPENTAD_PCOTMRAS_PREBACKBONE_C3_GATE_JSON",
        gate_sha256_env="OPENTAD_PCOTMRAS_PREBACKBONE_C3_GATE_SHA256",
        active_manifest_sha256_env="OPENTAD_PCOTMRAS_PREBACKBONE_C3_ACTIVE_MANIFEST_SHA256",
        resolved_config_sha256_env="OPENTAD_PCOTMRAS_PREBACKBONE_C3_RESOLVED_CONFIG_SHA256",
        require_resolved_config_sha256=True,
        allowed_decisions=("ALLOW_PC_OT_MRAS_PREBACKBONE_C3_FULL_TRAIN_FIXED50",),
        strict_payload_validation=True,
        required_exact_values=dict(
            route=route_id,
            variant_id=variant_id,
            execution_mode="train",
            selection_surface="pre_backbone_raw_frame",
            selection_timing="online_before_backbone",
            acquisition_unit="frame",
            claim_tier="no_deploy_until_runtime_audit",
            budget=window_size,
            dense_window_size=dense_window_size,
            selection_unit=selection_unit,
            scout_feature_source="compressed_pixels",
            scout_spatial_size=scout_spatial_size,
            max_epochs=60,
            checkpoint_interval=60,
            val_start_epoch=40,
            val_eval_interval=2,
        ),
        required_true_keys=(
            "allow_remote_sync",
            "allow_precheck_only",
            "allow_slurm",
            "allow_gpu",
            "single_gpu",
            "allow_prebackbone_frame_selector",
            "allow_joint_selector_detector_training",
            "allow_tools_train",
            "allow_dataset_access",
            "allow_pretrained_initialization",
            "allow_checkpoint_write",
            "allow_train_validation_map",
            "allow_long_training",
            "reader_trainable",
        ),
        required_false_keys=(
            "uses_p2",
            "uses_offline_ledger",
            "uses_teacher",
            "uses_test_gt",
            "uses_raw_prediction_cache",
        ),
        unknown_key_policy="reject_unknown_except_explicit_harmless_metadata",
        harmless_metadata_keys=(
            "note",
            "review_id",
            "run_tag",
            "pretrained_sha256",
        ),
        sha256_file_bindings=(
            dict(
                gate_key="pretrained_sha256",
                path_env="PC_OT_MRAS_PREBACKBONE_C3_PRETRAINED_PATH",
                label="pretrained",
            ),
        ),
        forbidden_true_keys=(
            "tools_test",
            "allow_tools_test",
            "direct_tools_test",
            "detector_map",
            "allow_detector_map",
            "formal_eval",
            "allow_formal_eval",
            "checkpoint_load",
            "allow_checkpoint_load",
            "resume",
            "allow_resume",
            "load_from",
            "allow_load_from",
            "offline_ledger",
            "allow_offline_ledger",
            "frozen_reader_ledger",
            "allow_frozen_reader_ledger",
            "post_projection_bridge",
            "allow_post_projection_bridge",
            "raw_prediction",
            "allow_raw_prediction",
            "raw_predictions",
            "allow_raw_predictions",
            "raw_prediction_cache",
            "allow_raw_prediction_cache",
            "prediction_cache",
            "allow_prediction_cache",
            "load_from_raw_predictions",
            "allow_load_from_raw_predictions",
            "save_raw_prediction",
            "allow_save_raw_prediction",
            "save_raw_predictions",
            "allow_save_raw_predictions",
            "uses_p2",
            "uses_teacher",
            "uses_oracle",
            "uses_test_gt",
            "uses_raw_prediction",
            "metric_claim",
            "allow_metric_claim",
            "metric_claim_allowed",
            "paper_claim",
            "allow_paper_claim",
            "paper_claim_allowed",
            "runtime_claim",
            "allow_runtime_claim",
            "flops_claim",
            "allow_flops_claim",
            "runtime_flops_claim",
            "allow_runtime_flops_claim",
            "runtime_flops_claim_allowed",
            "deploy_claim",
            "allow_deploy_claim",
            "deploy_claim_allowed",
        ),
    ),
    metric_claim_allowed=False,
    paper_claim_allowed=False,
    runtime_flops_claim_allowed=False,
    deploy_claim_allowed=False,
    allowed_entrypoints=("tools/train.py",),
)

model = dict(
    frame_selector=dict(
        target_len=window_size,
        dense_window_size=dense_window_size,
        descriptor_dim=scout_descriptor_dim,
        scout_feature_source="compressed_pixels",
        scout_spatial_size=scout_spatial_size,
        selection_unit=selection_unit,
        protected_uniform_count=0,
        coverage_guard_count=0,
        transport_topk=1,
        eval_transport_topk=1,
        straight_through_downstream=True,
        remap_gt_to_selected_axis=True,
        reader=dict(
            _delete_=True,
            type="PCOTMRASTinyTransformerFrameScout",
            in_dim=scout_descriptor_dim,
            hidden_dim=128,
            num_slots=window_size,
            num_layers=2,
            num_heads=4,
            dropout=0.0,
        ),
    ),
    backbone=dict(
        backbone=dict(total_frames=window_size),
        custom=dict(pretrain=pretrained_path),
    ),
    projection=dict(max_seq_len=window_size),
)

workflow = dict(
    logging_interval=50,
    checkpoint_interval=60,
    val_loss_interval=-1,
    val_eval_interval=2,
    val_start_epoch=40,
    end_epoch=60,
)

inference = dict(load_from_raw_predictions=False, save_raw_prediction=False)

work_dir = "exps/thumos/adatad/pc_ot_mras_prebackbone_c3_f1_lr_tinytransformer_st_original_adatad_full_train_candidate_n16r4"
